## টোকেনাইজেশন, অক্ষরগুলোকে সংখ্যায় আনছি ইউনিকোডে

In [2]:
c= '\u0980'
ord('আ') #use Order Function()


2438

In [3]:
print(c)

ঀ


In [4]:
chr(2495) #chr() method returns a character (a string) from an integer (represents unicode code point of the character)

'ি'

In [5]:
print(ord('ক'))
print(ord('ল'))
print(ord('স'))
print(ord(' '))

2453
2482
2488
32


ধরুন আমরা একটা শব্দ বলছি কলস, এর মধ্যে তিনটা অক্ষর আছে, যাকে আলাদা করে ইউনিকোড পয়েন্ট কোড হচ্ছে নিচের লাইনে।

In [6]:
import numpy as np
np.array([ord(char) for char in u"কলস"])

array([2453, 2482, 2488])

In [7]:
np.array([ord(char) for char in "কলস"])

array([2453, 2482, 2488])

In [8]:
import tensorflow as tf
tf.strings.unicode_decode("সকল", input_encoding='UTF-8')

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([2488, 2453, 2482], dtype=int32)>

In [9]:
tf.strings.unicode_decode('আমি ভালবাসি বই পড়তে', 'UTF-8')

<tf.Tensor: shape=(19,), dtype=int32, numpy=
array([2438, 2478, 2495,   32, 2477, 2494, 2482, 2476, 2494, 2488, 2495,
         32, 2476, 2439,   32, 2474, 2524, 2468, 2503], dtype=int32)>

In [10]:
from tensorflow.keras.preprocessing.text import Tokenizer
sentences = [
             'আমি ভালবাসি বই পড়তে।'
             ]
tokenizer = Tokenizer(num_words= 10, filters='!।')
print(tokenizer)

In [11]:
# tokenizer.fit_on_sequences(sentences)
# word_index = tokenizer.word_index
# print(word_index)

In [12]:
tokenizer.fit_on_texts(sentences)
word_index = tokenizer.word_index
print(word_index)

{'আমি': 1, 'ভালবাসি': 2, 'বই': 3, 'পড়তে': 4}


In [13]:
tokenizer.num_words

10

In [14]:
sentences = [
    'আমি ভালবাসি বই পড়তে।',
    'আমি ভালবাসি বই লিখতে!'
        ]

In [15]:
tokenizer.fit_on_texts(sentences)
word_index = tokenizer.word_index
print(word_index)

{'আমি': 1, 'ভালবাসি': 2, 'বই': 3, 'পড়তে': 4, 'লিখতে': 5}


In [16]:
tokenizer.word_counts

OrderedDict([('আমি', 3), ('ভালবাসি', 3), ('বই', 3), ('পড়তে', 2), ('লিখতে', 1)])

## tokenizer এর ভেতরের কনফিগারেশন


In [18]:
tokenizer.get_config()

{'char_level': False,
 'document_count': 3,
 'filters': '!।',
 'index_docs': '{"4": 2, "2": 3, "3": 3, "1": 3, "5": 1}',
 'index_word': '{"1": "\\u0986\\u09ae\\u09bf", "2": "\\u09ad\\u09be\\u09b2\\u09ac\\u09be\\u09b8\\u09bf", "3": "\\u09ac\\u0987", "4": "\\u09aa\\u09dc\\u09a4\\u09c7", "5": "\\u09b2\\u09bf\\u0996\\u09a4\\u09c7"}',
 'lower': True,
 'num_words': 10,
 'oov_token': None,
 'split': ' ',
 'word_counts': '{"\\u0986\\u09ae\\u09bf": 3, "\\u09ad\\u09be\\u09b2\\u09ac\\u09be\\u09b8\\u09bf": 3, "\\u09ac\\u0987": 3, "\\u09aa\\u09dc\\u09a4\\u09c7": 2, "\\u09b2\\u09bf\\u0996\\u09a4\\u09c7": 1}',
 'word_docs': '{"\\u09aa\\u09dc\\u09a4\\u09c7": 2, "\\u09ad\\u09be\\u09b2\\u09ac\\u09be\\u09b8\\u09bf": 3, "\\u09ac\\u0987": 3, "\\u0986\\u09ae\\u09bf": 3, "\\u09b2\\u09bf\\u0996\\u09a4\\u09c7": 1}',
 'word_index': '{"\\u0986\\u09ae\\u09bf": 1, "\\u09ad\\u09be\\u09b2\\u09ac\\u09be\\u09b8\\u09bf": 2, "\\u09ac\\u0987": 3, "\\u09aa\\u09dc\\u09a4\\u09c7": 4, "\\u09b2\\u09bf\\u0996\\u09a4\\u09c7": 5